interface FlagProps {
    tricolor?: boolean,
    linesHorizontal?: boolean,
    linesVertical?: boolean,
    colorWhite?: boolean,
    colorBlack?: boolean,
    colorRed?: boolean,
    colorGreen?: boolean,
    colorBlue?: boolean,
    colorYellow?: boolean,
    pictureCross?: boolean,
    pictureStar?: boolean,
    pictureCircle?: boolean,
    pictureTriangle?: boolean,
    pictureCrescent?: boolean,
    pictureOther?: boolean,
}

const getFlagProps = (input: FlagProps): FlagProps => {
    let defaultProps: FlagProps = {
        tricolor: false,
        linesHorizontal: false,
        linesVertical: false,
        colorWhite: false,
        colorBlack: false,
        colorRed: false,
        colorGreen: false,
        colorBlue: false,
        colorYellow: false,
        pictureCross: false,
        pictureStar: false,
        pictureCircle: false,
        pictureTriangle: false,
        pictureCrescent: false,
        pictureOther: false,
    };
    return {
        ...defaultProps,
        ...input
    };
};

export const FLAGS = [
    { name: 'Afghanistan', picture: 'Afghanistan.svg', props: getFlagProps({}) },
    { name: 'Albania', picture: 'Albania.svg', props: getFlagProps({}) },
    { name: 'Algeria', picture: 'Algeria.svg', props: getFlagProps({}) },
    { name: 'Andorra', picture: 'Andorra.svg', props: getFlagProps({}) },
    { name: 'Angola', picture: 'Angola.svg', props: getFlagProps({}) },
    { name: 'Antigua_and_Barbuda', picture: 'Antigua_and_Barbuda.svg', props: getFlagProps({}) },
    { name: 'Argentina', picture: 'Argentina.svg', props: getFlagProps({}) },
    { name: 'Armenia', picture: 'Armenia.svg', props: getFlagProps({}) },
    { name: 'Australia', picture: 'Australia.svg', props: getFlagProps({}) },
    { name: 'Austria', picture: 'Austria.svg', props: getFlagProps({}) },
    { name: 'Azerbaijan', picture: 'Azerbaijan.svg', props: getFlagProps({}) },
    { name: 'Bahrain', picture: 'Bahrain.svg', props: getFlagProps({}) },
    { name: 'Bangladesh', picture: 'Bangladesh.svg', props: getFlagProps({}) },
    { name: 'Barbados', picture: 'Barbados.svg', props: getFlagProps({}) },
    { name: 'Belarus', picture: 'Belarus.svg', props: getFlagProps({}) },
    { name: 'Belgium', picture: 'Belgium.svg', props: getFlagProps({}) },
    { name: 'Belize', picture: 'Belize.svg', props: getFlagProps({}) },
    { name: 'Benin', picture: 'Benin.svg', props: getFlagProps({}) },
    { name: 'Bhutan', picture: 'Bhutan.svg', props: getFlagProps({}) },
    { name: 'Bolivia', picture: 'Bolivia.svg', props: getFlagProps({}) },
    { name: 'Bosnia_and_Herzegovina', picture: 'Bosnia_and_Herzegovina.svg', props: getFlagProps({}) },
    { name: 'Botswana', picture: 'Botswana.svg', props: getFlagProps({}) },
    { name: 'Brazil', picture: 'Brazil.svg', props: getFlagProps({}) },
    { name: 'Brunei', picture: 'Brunei.svg', props: getFlagProps({}) },
    { name: 'Bulgaria', picture: 'Bulgaria.svg', props: getFlagProps({}) },
    { name: 'Burkina_Faso', picture: 'Burkina_Faso.svg', props: getFlagProps({}) },
    { name: 'Burundi', picture: 'Burundi.svg', props: getFlagProps({}) },
    { name: 'Cambodia', picture: 'Cambodia.svg', props: getFlagProps({}) },
    { name: 'Cameroon', picture: 'Cameroon.svg', props: getFlagProps({}) },
    { name: 'Canada', picture: 'Canada.svg', props: getFlagProps({}) },
    { name: 'Cape_Verde', picture: 'Cape_Verde.svg', props: getFlagProps({}) },
    { name: 'Chad', picture: 'Chad.svg', props: getFlagProps({}) },
    { name: 'Chile', picture: 'Chile.svg', props: getFlagProps({}) },
    { name: 'Colombia', picture: 'Colombia.svg', props: getFlagProps({}) },
    { name: 'Costa_Rica', picture: 'Costa_Rica.svg', props: getFlagProps({}) },
    { name: 'Croatia', picture: 'Croatia.svg', props: getFlagProps({}) },
    { name: 'Cuba', picture: 'Cuba.svg', props: getFlagProps({}) },
    { name: 'Cyprus', picture: 'Cyprus.svg', props: getFlagProps({}) },
    { name: 'Denmark', picture: 'Denmark.svg', props: getFlagProps({}) },
    { name: 'Djibouti', picture: 'Djibouti.svg', props: getFlagProps({}) },
    { name: 'Dominica', picture: 'Dominica.svg', props: getFlagProps({}) },
    { name: 'East_Timor', picture: 'East_Timor.svg', props: getFlagProps({}) },
    { name: 'Ecuador', picture: 'Ecuador.svg', props: getFlagProps({}) },
    { name: 'Egypt', picture: 'Egypt.svg', props: getFlagProps({}) },
    { name: 'El_Salvador', picture: 'El_Salvador.svg', props: getFlagProps({}) },
    { name: 'Equatorial_Guinea', picture: 'Equatorial_Guinea.svg', props: getFlagProps({}) },
    { name: 'Eritrea', picture: 'Eritrea.svg', props: getFlagProps({}) },
    { name: 'Estonia', picture: 'Estonia.svg', props: getFlagProps({}) },
    { name: 'Eswatini', picture: 'Eswatini.svg', props: getFlagProps({}) },
    { name: 'Ethiopia', picture: 'Ethiopia.svg', props: getFlagProps({}) },
    { name: 'Fiji', picture: 'Fiji.svg', props: getFlagProps({}) },
    { name: 'Finland', picture: 'Finland.svg', props: getFlagProps({}) },
    { name: 'France', picture: 'France.svg', props: getFlagProps({}) },
    { name: 'the_Bahamas', picture: 'the_Bahamas.svg', props: getFlagProps({}) },
    { name: 'the_Central_African_Republic', picture: 'the_Central_African_Republic.svg', props: getFlagProps({}) },
    { name: 'the_Comoros', picture: 'the_Comoros.svg', props: getFlagProps({}) },
    { name: 'the_Czech_Republic', picture: 'the_Czech_Republic.svg', props: getFlagProps({}) },
    {
        name: 'the_Democratic_Republic_of_the_Congo',
        picture: 'the_Democratic_Republic_of_the_Congo.svg',
        props: getFlagProps({})
    },
    { name: 'the_Dominican_Republic', picture: 'the_Dominican_Republic.svg', props: getFlagProps({}) },
];
